# Generated by Django 3.2.9 on 2022-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.IntegerField()),
                ('problem', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('preferred_time', models.IntegerField(choices=[(0, '8 AM to 12PM'), (1, '12 PM to 4 PM'), (2, '4 PM to 8 PM')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('customer_num', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('payment', models.IntegerField(choices=[(0, 'cash on delivery'), (1, 'online payment (you will receive it a text)')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_num', models.IntegerField()),
                ('book_request', models.CharField(max_length=100)),
            ],
        ),
    ]
