# Generated by Django 3.2.9 on 2022-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.IntegerField()),
                ('problem', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('preferred_time', models.IntegerField(choices=[(0, '8 AM to 12PM'), (1, '12 PM to 4 PM'), (2, '4 PM to 8 PM')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
