# Generated by Django 3.2.9 on 2022-01-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20220108_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('customer_num', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('payment', models.IntegerField(choices=[(0, 'cash on delivery'), (1, 'online payment (you will receive it a text')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
