# Generated by Django 3.2.9 on 2022-01-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20220109_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'cash on delivery'), (1, 'online payment (you will receive it a text)')], default=0),
        ),
    ]
